# Generated by Django 3.2.18 on 2023-05-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
